adjective1=input("enter an adjective(description of something): ")
noun1=input("enter a noun( is a name of person, place or thing): ")
adjective2=input("enter an adjective(description of something): ")
verb1=input("enter a verb ending with 'ing'. ")
adjective3=input("enter an adjective(description of something): ")

print(f"today i went a {adjective1} zoo. ")
print(f"in an exhibit,i saw {noun1}. ")
print(f"{noun1} was {adjective2} and {verb1} ")
print(f"i was {adjective3}! ")